// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4-vDYIcZ1No8yOTept9y-uRn4qV-BIJY',
    appId: '1:933972329643:web:d809379c7d26592fc9a3ee',
    messagingSenderId: '933972329643',
    projectId: 'projetolojaflutter-5b711',
    authDomain: 'projetolojaflutter-5b711.firebaseapp.com',
    storageBucket: 'projetolojaflutter-5b711.appspot.com',
    measurementId: 'G-JTY10NW6MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7L0jgmPHImJfEHbpU0RykTclj13046k',
    appId: '1:933972329643:android:bf33ed80d9ad8a29c9a3ee',
    messagingSenderId: '933972329643',
    projectId: 'projetolojaflutter-5b711',
    storageBucket: 'projetolojaflutter-5b711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVWjZsudFctt48GdS06Mgpqbw5bV_R4Go',
    appId: '1:933972329643:ios:5e2096f19f254296c9a3ee',
    messagingSenderId: '933972329643',
    projectId: 'projetolojaflutter-5b711',
    storageBucket: 'projetolojaflutter-5b711.appspot.com',
    iosBundleId: 'com.example.libelulas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVWjZsudFctt48GdS06Mgpqbw5bV_R4Go',
    appId: '1:933972329643:ios:d37ea9bd789777b5c9a3ee',
    messagingSenderId: '933972329643',
    projectId: 'projetolojaflutter-5b711',
    storageBucket: 'projetolojaflutter-5b711.appspot.com',
    iosBundleId: 'com.example.libelulas.RunnerTests',
  );
}
